language: cpp

os:
  - osx

dist: trusty

compiler:
  - clang

env:
  matrix:
    - QT=59 BREW=@5.9 PPA=beineri/opt-qt591-trusty

before_install:
  - '[ "$TRAVIS_OS_NAME" != osx   ] || brew update'

install:
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install cppcheck doxygen graphviz qt$BREW'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'
  - qmake -v

before_script:
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - cd "$TRAVIS_BUILD_DIR"/code
  - qmake qmltest.pro

script:
  - cd "$TRAVIS_BUILD_DIR"/code
  - make
  - macdeployqt qmltest.app
  - ls
  - zip qmltest.zip qmltest.app


