language: cpp

os:
  - osx

dist: trusty

compiler:
  - clang
  - gcc

env:
  matrix:
    - QT=59 BREW=@5.9 PPA=beineri/opt-qt591-trusty

before_install:
  - '[ "$TRAVIS_OS_NAME" != osx   ] || brew update'

install:
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install cppcheck doxygen graphviz qt$BREW'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'
  - qmake -v

before_script:
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - mkdir -p "$TRAVIS_BUILD_DIR-build"
  - qmake -o "$TRAVIS_BUILD_DIR-build" -r -Wall -Wlogic -Wparser CONFIG+=debug_and_release "$TRAVIS_BUILD_DIR"/code

script:
  - make -C "$TRAVIS_BUILD_DIR-build" all
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 check TESTARGS=-silent

