version: '{build}'

install:
  - set QTDIR=C:\Qt\5.8\msvc2015
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - cd code
  - qmake qmltest.pro
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64_x86
  - nmake
  - cd release
  - windeployqt qmltest.exe --no-translations --no-system-d3d-compiler --no-webkit2 --no-angle
  - dir
  - cd ..
  - 7z a qmltest.zip release
artifacts:
  - path: qmltest.zip
	name: qmltest.zip
